### ISSUE TITLE
Strange FMA Behavior

### ISSUE THREAD

**Issue by stmach** [pulp-platform/fpu#2] opened 2018-04-13 11:46 UTC
Issue submitted by email, formatted for better readability.

> Hello, I'm currently looking at the FPU from the pulp-platform GitHub (https://github.com/pulp-platform/fpu) and it behaves kind of strange in some cases.
> 
> For example one test case is the instruction `C_FPU_FMSUB_CMD` with inputs 1.0, 1.5 and 2.0: what I would expect here is that the result is -0.5 (=1.0*1.5-2.0), but the resulting output is -0.125 (`0xbe000000`) and the flags_o output is 0x1 (inexact).
> Why is this happening? The number -0.5 (`0xbf000000`) should be perfectly well representable without any rounding and is not even close to -0.125 so it doesn't make any sense to me unless I'm doing something wrong.
> 
> My setup is using CoCoTB (a Python framework that wraps the RTL simulator to simplify test development) with QuestaSim 10.4c as the backend.
> Inputs are driven as follows:
> `clk_i`: clock signal with 10ns period
> `reset_ni`: pulled low for 20ns then left high, I wait for the next positive clock edge before continuing to apply stimuli
> `fpu_en_i`: set to '1' for one clock cycle while providing input data then set to '0' while waiting for result
> `operand_a_i`: `0x3f800000` (1.0)
> `operand_b_i`: `0x3fc00000` (1.5)
> `operand_c_i`: `0x40000000` (2.0)
> `rm_i`: '0' (tried with all different values, did not matter for this case)
> `fpu_op_i`: `C_FPU_FMSUB_CMD` (0x9)
> `prec_i`: '0'
> 
> Outputs are sampled when valid_o goes high, after waiting for signals to stabilize ('readonly' phase).
> 
> The module fpu_private in file fpu_private.sv is used as the top level design with all parameters set to default values as of the pulpissimo-v1.0 release from GitHub.
> Similar behavior is also displayed in other cases like (-1.0 * 1.5 + 2.0) = 0.125 [`FMADD`], -(-1.0 * 1.5 + 2.0) = -0.125 [`FNMADD`], -(1.0 * 1.5 - 2.0) = 0.125 [`FNMSUB`]
> 
> Also taking the square root of 1 returns 1.125 which I found pretty strange, but that's probably due to an inaccurate approximation algorithm or something (and the fact that taking sqrt(1) is not a very useful thing to do apart from when testing)?

**Comment by tovine** [comment] 2018-04-13 13:26
When testing the proposed fix, I discovered one minor update/regression: the calculated results from the FMA seem to be correct now, but the inexact bit always seems to be set to `1`, regardless of whether it actually was a rounding performed.

One example (the test setup is using `fpu_private` as the top level):
Before:
```
#  1440.02ns INFO     cocotb.fpu_private                 .._private_cocotb.py:139  in run_test                        Testing op: fmadd
#  1460.02ns INFO     cocotb.rst_ni                      .._private_cocotb.py:96   in reset_gen                       Reset done
#  1465.02ns INFO     cocotb.fpu_private                 .._private_cocotb.py:154  in run_test                        Parameters: a=1.000000, b=1.500000, c=2.000000
#  1485.02ns INFO     cocotb.result_o                    .._private_cocotb.py:185  in run_test                        01000000011000000000000000000000
#  1485.02ns INFO     cocotb.valid_o                     .._private_cocotb.py:186  in run_test                        1
#  1485.02ns INFO     cocotb.flags_o                     .._private_cocotb.py:187  in run_test                        00000
#  1485.02ns INFO     cocotb.result_o                    .._private_cocotb.py:189  in run_test                        Result: 3.500000
```
After:
```
#  1440.02ns INFO     cocotb.fpu_private                 .._private_cocotb.py:139  in run_test                        Testing op: fmadd
#  1460.02ns INFO     cocotb.rst_ni                      .._private_cocotb.py:96   in reset_gen                       Reset done
#  1465.02ns INFO     cocotb.fpu_private                 .._private_cocotb.py:154  in run_test                        Parameters: a=1.000000, b=1.500000, c=2.000000
#  1485.02ns INFO     cocotb.result_o                    .._private_cocotb.py:185  in run_test                        01000000011000000000000000000000
#  1485.02ns INFO     cocotb.valid_o                     .._private_cocotb.py:186  in run_test                        1
#  1485.02ns INFO     cocotb.flags_o                     .._private_cocotb.py:187  in run_test                        00001
#  1485.02ns INFO     cocotb.result_o                    .._private_cocotb.py:189  in run_test                        Result: 3.500000
```

**Comment by stmach** [comment] 2018-04-13 16:49
I added the fix for the NX flag to #3. Will merge as soon as we sort out our access rights.

**Comment by tovine** [comment] 2018-04-19 08:27
When testing more today I discovered another edge-case that may be incorrect:
```
#  1935.04ns INFO     cocotb.fpu_private                 .._private_cocotb.py:139  in run_test                        Testing op: fnmsub
#  1955.04ns INFO     cocotb.rst_ni                      .._private_cocotb.py:96   in reset_gen                       Reset done
#  1960.04ns INFO     cocotb.fpu_private                 .._private_cocotb.py:154  in run_test                        Parameters: a=4.000000, b=1.500000, c=2.000000
#  1970.04ns DEBUG    cocotb.fpu_private                 .._private_cocotb.py:167  in run_test                        valid_o = 0, divsqrt_busy_o = 1, result_o = 00000000000000000000000000000000, flags_o = 00000
#  1980.04ns INFO     cocotb.result_o                    .._private_cocotb.py:185  in run_test                        11000000100000000000000000000000
#  1980.04ns INFO     cocotb.valid_o                     .._private_cocotb.py:186  in run_test                        1
#  1980.04ns INFO     cocotb.flags_o                     .._private_cocotb.py:187  in run_test                        00001
#  1980.04ns INFO     cocotb.result_o                    .._private_cocotb.py:189  in run_test                        Result: -4.000000
```
And similarly
```
#  1665.03ns INFO     cocotb.fpu_private                 .._private_cocotb.py:139  in run_test                        Testing op: fmsub
#  1685.03ns INFO     cocotb.rst_ni                      .._private_cocotb.py:96   in reset_gen                       Reset done
#  1690.03ns INFO     cocotb.fpu_private                 .._private_cocotb.py:154  in run_test                        Parameters: a=4.000000, b=1.500000, c=2.000000
#  1700.03ns DEBUG    cocotb.fpu_private                 .._private_cocotb.py:167  in run_test                        valid_o = 0, divsqrt_busy_o = 1, result_o = 00000000000000000000000000000000, flags_o = 00000
#  1710.03ns INFO     cocotb.result_o                    .._private_cocotb.py:185  in run_test                        01000000100000000000000000000000
#  1710.03ns INFO     cocotb.valid_o                     .._private_cocotb.py:186  in run_test                        1
#  1710.03ns INFO     cocotb.flags_o                     .._private_cocotb.py:187  in run_test                        00001
#  1710.03ns INFO     cocotb.result_o                    .._private_cocotb.py:189  in run_test                        Result: 4.000000
```
The output result is correct, but the NX flag seems a bit out of place here (all the intermediate results seem perfectly representable without rounding: `4.0`, `1.5`, `6.0`)?
Most of the previous NX errors were now fixed, this is the only one of my test cases that still fails.
Note that I have not yet run several tests with random data so I don't have any statistics on how widespread the problem actually is, only that it is still there part of the time.

**Closed as completed** 2018-04-19 13:11 UTC
